### ISSUE TITLE
build instructions?

### ISSUE THREAD

**Issue by 7yl4r** [nmfs-fish-tools/DisMAP#1]
How is the web application built from this? 

A quick glance at the code has me thinking that these are just data munging scripts.

**Comment by k-doering-NOAA** [comment]
Hi @7yl4r , I see this in the readme:


>This repository provides the data processing and analysis code used to develop the spatial distribution and indicators presented in the portal. For more information and to launch the portal visit: https://apps-st.fisheries.noaa.gov/dismap/index.html.

I think you are correct that the web application is not built from this code.
